export default {
    products: [
        {
            "id": "1",
            "name": "Refined Steel Shoes",
            "image": "https://picsum.photos/640/480",
            "price": "849.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 82644,
            "cateId":1,
        },
        {
            "id": "2",
            "name": "Tasty Concrete Chips",
            "image": "https://picsum.photos/640/480",
            "price": "762.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 57587,
            "cateId":1,
        },
        {
            "id": "3",
            "name": "Awesome Soft Fish",
            "image": "https://picsum.photos/640/480",
            "price": "633.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 51117,
            "cateId":3,
        },
        {
            "id": "4",
            "name": "Gorgeous Concrete Car",
            "image": "https://picsum.photos/640/480",
            "price": "728.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 56,
            "cateId":3,
        },
        {
            "id": "5",
            "name": "Fantastic Fresh Fish",
            "image": "https://picsum.photos/640/480",
            "price": "364.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 7373,
            "cateId":1,
        },
        {
            "id": "6",
            "name": "Gorgeous Metal Soap",
            "image": "https://picsum.photos/640/480",
            "price": "654.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 26,
            "cateId":2,
        },
        {
            "id": "7",
            "name": "Tasty Fresh Pizza",
            "image": "https://picsum.photos/640/480",
            "price": "795.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 61,
            "cateId":2,
        },
        {
            "id": "8",
            "name": "Tasty Concrete Towels",
            "image": "https://picsum.photos/640/480",
            "price": "513.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 36,
            "cateId":3,
        },
        {
            "id": "9",
            "name": "Awesome Metal Computer",
            "image": "https://picsum.photos/640/480",
            "price": "741.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 29,
            "cateId":1,
        },
        {
            "id": "10",
            "name": "Small Rubber Cheese",
            "image": "https://picsum.photos/640/480",
            "price": "471.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 42,
            "cateId":1,
        },
        {
            "id": "11",
            "name": "Handcrafted Soft Salad",
            "image": "https://picsum.photos/640/480",
            "price": "824.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 86,
            "cateId":3,
        },
        {
            "id": "12",
            "name": "Licensed Steel Soap",
            "image": "https://picsum.photos/640/480",
            "price": "611.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 14,
            "cateId":1,
        },
        {
            "id": "13",
            "name": "Handmade Frozen Ball",
            "image": "https://picsum.photos/640/480",
            "price": "821.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 64,
            "cateId":2,
        },
        {
            "id": "14",
            "name": "Handmade Plastic Table",
            "image": "https://picsum.photos/640/480",
            "price": "894.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 94,
            "cateId":3,
        },
        {
            "id": "15",
            "name": "Generic Fresh Gloves",
            "image": "https://picsum.photos/640/480",
            "price": "156.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 13,
            "cateId":1,
        },
        {
            "id": "16",
            "name": "Generic Soft Keyboard",
            "image": "https://picsum.photos/640/480",
            "price": "933.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": true,
            "quantity": 64,
            "cateId":2,
        },
        {
            "id": "17",
            "name": "Intelligent Granite Table",
            "image": "https://picsum.photos/640/480",
            "price": "694.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 65,
            "cateId":1,
        },
        {
            "id": "18",
            "name": "Small Soft Shirt",
            "image": "https://picsum.photos/640/480",
            "price": "797.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 22,
            "cateId":3,
        },
        {
            "id": "19",
            "name": "Rustic Metal Table",
            "image": "https://picsum.photos/640/480",
            "price": "841.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 98,
            "cateId":1,
        },
        {
            "id": "20",
            "name": "Incredible Soft Mouse",
            "image": "https://picsum.photos/640/480",
            "price": "828.00",
            "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, perferendis!",
            "status": false,
            "quantity": 63,
            "cateId":2,
        }
    ],
    category: [
        {"id":"1", name:'category 1'},
        {"id":"2", name:'category 2'},
        {"id":"3", name:'category 3'}
    ]
}